# here i have to print unique number only from 10 numbers given by users
n1=int(input("Enter number"))
n2=int(input("Enter number"))
n3=int(input("Enter number"))
n4=int(input("Enter number"))
n5=int(input("Enter number"))
n6=int(input("Enter number"))
n7=int(input("Enter number"))
n8=int(input("Enter number"))
n9=int(input("Enter number"))
n10=int(input("Enter number"))
b=set()
b.add(n1)
b.add(n2)
b.add(n3)
b.add(n4)
b.add(n5)
b.add(n6)
b.add(n7)
b.add(n8)
b.add(n9)
b.add(n10)
print(b)
print(len(b))